// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBThzZ5_nPXTSLEMe1dZfOHZGT4836OBp8',
    appId: '1:964178693004:web:cc95fde98a7f781100a4a9',
    messagingSenderId: '964178693004',
    projectId: 'cashewguard-ai',
    authDomain: 'cashewguard-ai.firebaseapp.com',
    storageBucket: 'cashewguard-ai.firebasestorage.app',
    measurementId: 'G-QCNJFYMXQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE8509x9jXbvliKh4ZcfHvjGok15FK508',
    appId: '1:964178693004:android:46481fd288e4690600a4a9',
    messagingSenderId: '964178693004',
    projectId: 'cashewguard-ai',
    storageBucket: 'cashewguard-ai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4e7cK9mWaVA35DWjCulLlUza1Y2tYIrY',
    appId: '1:964178693004:ios:237a2a24f0efac1e00a4a9',
    messagingSenderId: '964178693004',
    projectId: 'cashewguard-ai',
    storageBucket: 'cashewguard-ai.firebasestorage.app',
    iosBundleId: 'com.example.cashewguardAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4e7cK9mWaVA35DWjCulLlUza1Y2tYIrY',
    appId: '1:964178693004:ios:237a2a24f0efac1e00a4a9',
    messagingSenderId: '964178693004',
    projectId: 'cashewguard-ai',
    storageBucket: 'cashewguard-ai.firebasestorage.app',
    iosBundleId: 'com.example.cashewguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBThzZ5_nPXTSLEMe1dZfOHZGT4836OBp8',
    appId: '1:964178693004:web:7ffd6768d000065f00a4a9',
    messagingSenderId: '964178693004',
    projectId: 'cashewguard-ai',
    authDomain: 'cashewguard-ai.firebaseapp.com',
    storageBucket: 'cashewguard-ai.firebasestorage.app',
    measurementId: 'G-DNFVJWC9FH',
  );
}
